import { useRouter, type Href } from 'expo-router';
import { useCallback, useMemo } from 'react';
import { Text, View } from 'react-native';

import { useStartSession } from '@/api/hooks/useSessions';
import { QUESTS, pickRandomQuest } from '@/components/detox/quests';
import { PressableScale } from '@/components/ui/PressableScale';
import { Card, Screen, SectionLabel } from '@/components/ui/Screen';
import { ChevronRight, ShieldOff } from '@/components/ui/icons';
import { haptics } from '@/lib/haptics';
import { stopPlayback } from '@/services/audioPlayer';
import {
  clearCompletedTimer,
  formatDuration,
  useCountdown,
  useTimerControls,
} from '@/services/timerEngine';
import { useEnergyStore } from '@/store/useEnergyStore';
import { accents, layout, palette } from '@/theme/tokens';

const DURATIONS = [
  { label: '20 хв', ms: 20 * 60 * 1000 },
  { label: '30 хв', ms: 30 * 60 * 1000 },
  { label: '60 хв', ms: 60 * 60 * 1000 },
] as const;

// Cast because expo-router's generated route union does not yet include this
// freshly-added modal until its types are regenerated by the dev server.
const ZEN_ROUTE = '/modal/detox-zen' as Href;

export default function DetoxScreen() {
  const router = useRouter();
  const { timer, remaining, isRunning } = useCountdown(handleComplete);
  const controls = useTimerControls();

  const armDetox = useEnergyStore((s) => s.armDetox);
  const releaseDetox = useEnergyStore((s) => s.releaseDetox);
  const { mutateAsync: startSession } = useStartSession();

  const isDetoxRunning = isRunning && timer?.kind === 'detox';

  // The Detox tab owns completion even when the Zen modal is open above it, so
  // the success haptic and the timer clear happen exactly once.
  function handleComplete() {
    releaseDetox();
    haptics.success();
    clearCompletedTimer();
  }

  const begin = useCallback(
    async (durationMs: number, label: string) => {
      await startSession({ type: 'detox', plannedDurationMs: durationMs });
      // Silence first: a detox window with a soundscape still running is not one.
      await stopPlayback();
      armDetox();
      await controls.start('detox', `Глибокий офлайн · ${label}`, durationMs);
      // Straight into Zen mode — put the phone down.
      router.push(ZEN_ROUTE);
    },
    [armDetox, controls, router, startSession],
  );

  const endEarly = useCallback(async () => {
    await controls.cancel();
    releaseDetox();
    haptics.warn();
  }, [controls, releaseDetox]);

  // One preview quest per visit — the real one is re-rolled when Zen mode opens.
  const quest = useMemo(() => pickRandomQuest(), []);
  const QuestIcon = quest.icon;

  return (
    <Screen title="Детокс" subtitle="Відклади телефон. Тут тебе ніщо не чекає.">
      {isDetoxRunning && timer ? (
        <>
          <Card className="mb-4 items-center py-8">
            <Text className="text-[11px] uppercase tracking-[1.6px] text-ink-mute">Глибокий офлайн</Text>
            <Text
              className="mt-3 text-[64px] font-extralight tracking-tighter"
              style={{ color: accents.detox, fontVariant: ['tabular-nums'] }}
            >
              {formatDuration(remaining)}
            </Text>
            <Text className="mt-4 text-center text-[13px] leading-[19px] text-ink-soft">
              Ми надішлемо одне сповіщення, коли вікно закриється. До того часу перевіряти нічого.
            </Text>
          </Card>

          <PressableScale onPress={() => router.push(ZEN_ROUTE)} haptic="none" className="mx-5 mb-3">
            <View
              className="flex-row items-center justify-center rounded-card border py-4"
              style={{ borderColor: `${accents.detox}55`, backgroundColor: `${accents.detox}14` }}
            >
              <ShieldOff size={17} strokeWidth={layout.iconStroke} color={accents.detox} />
              <Text className="ml-2 text-[14px] font-semibold" style={{ color: accents.detox }}>
                Відкрити Zen-режим
              </Text>
            </View>
          </PressableScale>

          <PressableScale onPress={() => void endEarly()} className="mx-5 mb-6">
            <View className="items-center rounded-card border border-hairline py-4">
              <Text className="text-[14px] font-medium text-ink-mute">Завершити достроково</Text>
            </View>
          </PressableScale>
        </>
      ) : (
        <>
          <SectionLabel>Глибокий офлайн</SectionLabel>
          <View className="mx-5 mb-6 flex-row gap-3">
            {DURATIONS.map((option) => (
              <PressableScale
                key={option.label}
                className="flex-1"
                onPress={() => void begin(option.ms, option.label)}
                scaleTo={0.95}
              >
                <View
                  className="items-center rounded-card border py-5"
                  style={{ borderColor: `${accents.detox}55`, backgroundColor: `${accents.detox}14` }}
                >
                  <ShieldOff size={19} strokeWidth={layout.iconStroke} color={accents.detox} />
                  <Text className="mt-2 text-[14px] font-semibold" style={{ color: accents.detox }}>
                    {option.label}
                  </Text>
                </View>
              </PressableScale>
            ))}
          </View>
        </>
      )}

      {/* Preview of the analog quest */}
      <SectionLabel>Аналоговий мікроквест</SectionLabel>
      <Card className="mb-6">
        <View className="flex-row items-start">
          <View
            className="h-12 w-12 items-center justify-center rounded-pill"
            style={{ backgroundColor: `${accents.detox}1F` }}
          >
            <QuestIcon size={22} strokeWidth={layout.iconStroke} color={accents.detox} />
          </View>
          <View className="ml-4 flex-1">
            <Text className="text-[16px] font-semibold leading-[22px] text-ink">{quest.title}</Text>
            <Text className="mt-1 text-[13px] leading-[19px] text-ink-soft">{quest.detail}</Text>
          </View>
          <ChevronRight size={18} strokeWidth={layout.iconStroke} color={palette.inkGhost} />
        </View>
      </Card>

      <SectionLabel>Інші заняття для рук</SectionLabel>
      <View className="mx-5 gap-2">
        {QUESTS.filter((q) => q.title !== quest.title).map((item) => {
          const ItemIcon = item.icon;
          return (
            <View
              key={item.title}
              className="flex-row items-center rounded-card border border-hairline bg-surface px-4 py-3.5"
            >
              <ItemIcon size={17} strokeWidth={layout.iconStroke} color={palette.inkMute} />
              <Text className="ml-3 flex-1 text-[14px] text-ink-soft">{item.title}</Text>
            </View>
          );
        })}
      </View>
    </Screen>
  );
}
